apiVersion: v1  
kind: Service   
metadata:
  name: connectify-record-mysql
spec:
  selector:
    app: connectify-record-mysql
  ports:
    - protocol: TCP      
      port: 3308         # Service exposed port
      targetPort: 3306   # Forward to Pod target port
  type: LoadBalancer     
  